name: dart_jwt_token
description: This package is used to create jwt token, verify token with key, and decode without key.
version: 0.0.3
repository: https://github.com/dizayn3r/Dart-JWT

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  crypto: ^3.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0